services:
  educationhistory-lib-unb-ca:
    build:
      target: development
      context: .
    container_name: educationhistory-lib-unb-ca
    volumes:
      - ./.nuxt:/nuxt/.nuxt
      - ./app:/nuxt/app
      - ./content:/nuxt/content
      - ./public:/nuxt/public
      - ./content.config.ts:/nuxt/content.config.ts
      - ./nuxt.config.ts:/nuxt/nuxt.config.ts
      - ./package.json:/nuxt/package.json
      - ./pnpm-lock.yaml:/nuxt/pnpm-lock.yaml
    environment:
      NUXT_SITE_URI: ${NUXT_SITE_URI}
      NUXT_PORT: ${NUXT_PORT}
    ports:
      - '3084:3084'
      - '30840:30840'
    networks:
      - educationhistory.lib.unb.ca

networks:
  educationhistory.lib.unb.ca:
    name: educationhistory.lib.unb.ca
