edu_history.settings:
  type: config_object
  label: 'Edu History settings'
  mapping:
    features:
      type: mapping
      label: 'Feature flags'
      mapping:
        node_user_picture:
          type: boolean
          label: 'Node user picture'
        comment_user_picture:
          type: boolean
          label: 'Comment user picture'
        comment_user_verification:
          type: boolean
          label: 'Comment user verification'
        favicon:
          type: boolean
          label: 'Favicon enabled'
    logo:
      type: mapping
      label: 'Logo'
      mapping:
        use_default:
          type: boolean
          label: 'Use default logo'
        path:
          type: string
          label: 'Logo path'
    favicon:
      type: mapping
      label: 'Favicon'
      mapping:
        use_default:
          type: boolean
          label: 'Use default favicon'
        path:
          type: string
          label: 'Favicon path'
        mimetype:
          type: string
          label: 'Favicon mimetype'