name: Deploy educationhistory.lib.unb.ca

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: unb-libraries/github-workflows/.github/workflows/build-push-deploy-notify.yaml@1.x
    with:
      branch-env-map: '{"dev":"dev"}'
      deploy-branches: '["dev"]'
      image-name: ghcr.io/unb-libraries/educationhistory.lib.unb.ca
      k8s-deployment-name: educationhistory-lib-unb-ca
      platforms: linux/amd64
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GH_CONTAINER_REGISTRY_USER: ${{ secrets.GH_CONTAINER_REGISTRY_USER }}
      GH_CONTAINER_REGISTRY_TOKEN: ${{ secrets.GH_CONTAINER_REGISTRY_TOKEN }}
